global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using MMDataAccess.Configuration;
global using MMDataAccess.Data;
global using MMDataAccess.Enums;
global using MMDataAccess.Interfaces.CommandHandlers;
global using MMDataAccess.Interfaces.QueryHandlers;
global using MMDataAccess.Models;
global using MMDataAccess.ModelsSummary;
