CREATE TABLE [dbo].[MyMM]
(
	MyMMId INT NOT NULL IDENTITY(1,1),
	Title NVARCHAR(50) NOT NULL,
	URL NVARCHAR(255) NULL,
	Notes NVARCHAR(500) NULL,
	ActionDate DATETIME2 NULL,
	IsExternal BIT NOT NULL,
	StatusId INT NOT NULL,
	CONSTRAINT [PK_MyMM] PRIMARY KEY (MyMMId),
	CONSTRAINT [FK_MyMM_MyMMStatus] FOREIGN KEY (StatusId)
		REFERENCES [dbo].[MyMMStatus] (StatusId)
)
