IF NOT EXISTS (SELECT 1 FROM Language)
BEGIN
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Afar', N'Qafar', N'Qafar', 'aa');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Abkhazian', N'Аҧсны́', N'Apsny', 'ab');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Avestan', N'𐬀𐬬𐬀𐬯𐬙𐬀𐬥', N'Avesta', 'ae');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Afrikaans', N'Afrikaans', N'Afrikaans', 'af');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Akan', N'Akan', N'Akan', 'ak');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Amharic', N'አማርኛ', N'Amarəñña', 'am');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Aragonese', N'Aragonés', N'Aragonés', 'an');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Arabic', N'العربية', N'al-ʿArabīyah', 'ar');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Assamese', N'অসমীয়া', N'Ôxômiya', 'as');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Avaric', N'Авар', N'Avar', 'av');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Aymara', N'Aymar aru', N'Aymara', 'ay');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Azerbaijani', N'Azərbaycan dili', N'Azərbaycan dili', 'az');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Bashkir', N'Башҡортса', N'Başqortsa', 'ba');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Belarusian', N'Беларуская', N'Bielaruskaja', 'be');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Bulgarian', N'Български', N'Bălgarski', 'bg');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Bihari', N'भोजपुरी', N'Bhojpurī', 'bh');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Bislama', N'Bislama', N'Bislama', 'bi');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Bambara', N'Bamanankan', N'Bamanankan', 'bm');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Bengali', N'বাংলা', N'Bangla', 'bn');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Tibetan', N'བོད་སྐད་', N'Bodskad', 'bo');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Breton', N'Brezhoneg', N'Brezhoneg', 'br');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Bosnian', N'Bosanski', N'Bosanski', 'bs');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Catalan', N'Català', N'Català', 'ca');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Chechen', N'Нохчийн мотт', N'Noxçiyn mott', 'ce');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Chamorro', N'Chamoru', N'Chamoru', 'ch');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Corsican', N'Corsu', N'Corsu', 'co');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Cree', N'ᓀᐦᐃᔭᐍᐏᐣ', N'Nēhiyawēwin', 'cr');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Czech', N'Čeština', N'Čeština', 'cs');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Church Slavic', N'словѣ́ньскъ', N'Slověnĭskŭ', 'cu');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Chuvash', N'Чӑвашла', N'Čăvašla', 'cv');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Welsh', N'Cymraeg', N'Cymraeg', 'cy');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Danish', N'Dansk', N'Dansk', 'da');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'German', N'Deutsch', N'Deutsch', 'de');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Dhivehi', N'ދިވެހި', N'Dhivehi', 'dv');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Dzongkha', N'རྫོང་ཁ', N'Dzongkha', 'dz');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Greek', N'Ελληνικά', N'Elliniká', 'el');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'English', N'English', N'English', 'en');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Esperanto', N'Esperanto', N'Esperanto', 'eo');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Spanish', N'Español', N'Español', 'es');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Estonian', N'Eesti', N'Eesti', 'et');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Basque', N'Euskara', N'Euskara', 'eu');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Persian', N'فارسی', N'Fārsī', 'fa');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Fulah', N'Pulaar', N'Pulaar', 'ff');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Finnish', N'Suomi', N'Suomi', 'fi');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Fijian', N'Vosa Vakaviti', N'Vosa Vakaviti', 'fj');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Faroese', N'Føroyskt', N'Føroyskt', 'fo');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'French', N'Français', N'Français', 'fr');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Western Frisian', N'Frysk', N'Frysk', 'fy');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Irish', N'Gaeilge', N'Gaeilge', 'ga');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Gaelic (Scottish)', N'Gàidhlig', N'Gàidhlig', 'gd');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Galician', N'Galego', N'Galego', 'gl');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Guaraní', N'Avañe''ẽ', N'Avañe''ẽ', 'gn');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Gujarati', N'ગુજરાતી', N'Gujarātī', 'gu');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Manx', N'Gaelg', N'Gaelg', 'gv');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Hausa', N'Hausa', N'Hausa', 'ha');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Hebrew', N'עברית', N'ʿIvrit', 'he');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Hindi', N'हिन्दी', N'Hindī', 'hi');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Hiri Motu', N'Hiri Motu', N'Hiri Motu', 'ho');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Croatian', N'Hrvatski', N'Hrvatski', 'hr');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Haitian Creole', N'Kreyòl Ayisyen', N'Kreyòl Ayisyen', 'ht');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Hungarian', N'Magyar', N'Magyar', 'hu');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Armenian', N'Հայերեն', N'Hayeren', 'hy');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Herero', N'Otjiherero', N'Otjiherero', 'hz');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Interlingua', N'Interlingua', N'Interlingua', 'ia');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Indonesian', N'Bahasa Indonesia', N'Bahasa Indonesia', 'id');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Interlingue', N'Interlingue', N'Interlingue', 'ie');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Igbo', N'Igbo', N'Igbo', 'ig');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Sichuan Yi', N'ꆈꌠꉙ', N'Nuosu', 'ii');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Inupiaq', N'Iñupiaq', N'Iñupiaq', 'ik');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Ido', N'Ido', N'Ido', 'io');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Icelandic', N'Íslenska', N'Íslenska', 'is');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Italian', N'Italiano', N'Italiano', 'it');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Inuktitut', N'ᐃᓄᒃᑎᑐᑦ', N'Inuktitut', 'iu');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Japanese', N'日本語', N'Nihongo', 'ja');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Javanese', N'ꦧꦱꦗꦮ', N'Basa Jawa', 'jv');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Georgian', N'ქართული', N'Kartuli', 'ka');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Kongo', N'Kikongo', N'Kikongo', 'kg');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Kikuyu', N'Gĩkũyũ', N'Gikuyu', 'ki');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Kuanyama', N'Oshikwanyama', N'Oshikwanyama', 'kj');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Kazakh', N'Қазақ тілі', N'Qazaq tili', 'kk');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Kalaallisut', N'Kalaallisut', N'Kalaallisut', 'kl');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Khmer', N'ខ្មែរ', N'Khmer', 'km');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Kannada', N'ಕನ್ನಡ', N'Kannada', 'kn');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Korean', N'한국어', N'Hangugeo', 'ko');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Kanuri', N'Kanuri', N'Kanuri', 'kr');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Kashmiri', N'कश्मीरी', N'Kaśmīrī', 'ks');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Kurdish', N'Kurdî', N'Kurdî', 'ku');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Komi', N'Коми кыв', N'Komi kyv', 'kv');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Cornish', N'Kernewek', N'Kernewek', 'kw');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Kirghiz', N'Кыргызча', N'Kyrgyzcha', 'ky');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Latin', N'Latina', N'Latina', 'la');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Luxembourgish', N'Lëtzebuergesch', N'Lëtzebuergesch', 'lb');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Ganda', N'Luganda', N'Luganda', 'lg');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Limburgish', N'Limburgs', N'Limburgs', 'li');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Lingala', N'Lingála', N'Lingála', 'ln');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Lao', N'ລາວ', N'Lao', 'lo');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Lithuanian', N'Lietuvių', N'Lietuvių', 'lt');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Latvian', N'Latviešu', N'Latviešu', 'lv');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Malagasy', N'Malagasy', N'Malagasy', 'mg');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Marshallese', N'Kajin M̧ajeļ', N'Kajin Majel', 'mh');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Māori', N'Māori', N'Māori', 'mi');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Macedonian', N'Македонски', N'Makedonski', 'mk');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Malayalam', N'മലയാളം', N'Malayāḷaṁ', 'ml');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Mongolian', N'Монгол хэл', N'Mongol khel', 'mn');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Marathi', N'मराठी', N'Marāṭhī', 'mr');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Malay', N'Bahasa Melayu', N'Bahasa Melayu', 'ms');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Maltese', N'Malti', N'Malti', 'mt');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Burmese', N'မြန်မာစာ', N'Mranmāca', 'my');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Nauru', N'Dorerin Naoero', N'Dorerin Naoero', 'na');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Norwegian Bokmål', N'Bokmål', N'Bokmål', 'nb');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'North Ndebele', N'IsiNdebele', N'IsiNdebele', 'nd');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Nepali', N'नेपाली', N'Nepālī', 'ne');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Ndonga', N'Oshindonga', N'Oshindonga', 'ng');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Dutch', N'Nederlands', N'Nederlands', 'nl');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Norwegian Nynorsk', N'Nynorsk', N'Nynorsk', 'nn');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Norwegian', N'Norsk', N'Norsk', 'no');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'South Ndebele', N'IsiNdebele', N'IsiNdebele', 'nr');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Navajo', N'Diné Bizaad', N'Diné Bizaad', 'nv');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Chichewa', N'Chichewa', N'Chichewa', 'ny');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Occitan', N'Occitan', N'Occitan', 'oc');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Ojibwa', N'Ojibwe', N'Ojibwe', 'oj');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Oromo', N'Afaan Oromoo', N'Afaan Oromoo', 'om');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Oriya', N'ଓଡ଼ିଆ', N'Oṛiyā', 'or');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Ossetian', N'Ирон æвзаг', N'Iron ævzag', 'os');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Punjabi', N'ਪੰਜਾਬੀ', N'Pañjābī', 'pa');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Pāli', N'पालि', N'Pāli', 'pi');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Polish', N'Polski', N'Polski', 'pl');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Pashto', N'پښتو', N'Paṣhto', 'ps');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Portuguese', N'Português', N'Português', 'pt');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Quechua', N'Runasimi', N'Runasimi', 'qu');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Romansh', N'Rumantsch', N'Rumantsch', 'rm');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Rundi', N'Ikirundi', N'Ikirundi', 'rn');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Romanian', N'Română', N'Română', 'ro');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Russian', N'Русский', N'Russkiy', 'ru');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Kinyarwanda', N'Ikinyarwanda', N'Ikinyarwanda', 'rw');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Sanskrit', N'संस्कृतम्', N'Saṃskṛtam', 'sa');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Sardinian', N'Sardu', N'Sardu', 'sc');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Sindhi', N'سنڌي', N'Sindhī', 'sd');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Northern Sami', N'Davvisámegiella', N'Davvisámegiella', 'se');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Sango', N'Sängö', N'Sängö', 'sg');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Sinhala', N'සිංහල', N'Siṃhala', 'si');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Slovak', N'Slovenčina', N'Slovenčina', 'sk');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Slovenian', N'Slovenščina', N'Slovenščina', 'sl');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Samoan', N'Gagana Samoa', N'Gagana Samoa', 'sm');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Shona', N'ChiShona', N'ChiShona', 'sn');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Somali', N'Soomaali', N'Soomaali', 'so');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Albanian', N'Shqip', N'Shqip', 'sq');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Serbian', N'Српски', N'Srpski', 'sr');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Swati', N'SiSwati', N'SiSwati', 'ss');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Sotho (Southern)', N'Sesotho', N'Sesotho', 'st');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Sundanese', N'Basa Sunda', N'Basa Sunda', 'su');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Swedish', N'Svenska', N'Svenska', 'sv');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Swahili', N'Kiswahili', N'Kiswahili', 'sw');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Tamil', N'தமிழ்', N'Tamiḻ', 'ta');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Telugu', N'తెలుగు', N'Telugu', 'te');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Tajik', N'Тоҷикӣ', N'Toǰikī', 'tg');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Thai', N'ไทย', N'Thai', 'th');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Tigrinya', N'ትግርኛ', N'Tigrinya', 'ti');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Turkmen', N'Türkmençe', N'Türkmençe', 'tk');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Tagalog', N'Tagalog', N'Tagalog', 'tl');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Tswana', N'Setswana', N'Setswana', 'tn');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Tonga', N'Faka Tonga', N'Faka Tonga', 'to');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Turkish', N'Türkçe', N'Türkçe', 'tr');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Tsonga', N'Xitsonga', N'Xitsonga', 'ts');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Tatar', N'Татарча', N'Tatarça', 'tt');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Twi', N'Twi', N'Twi', 'tw');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Tahitian', N'Reo Tahiti', N'Reo Tahiti', 'ty');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Uighur', N'ئۇيغۇرچە', N'Uyghurche', 'ug');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Ukrainian', N'Українська', N'Ukrayinsʹka', 'uk');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Urdu', N'اردو', N'Urdū', 'ur');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Uzbek', N'Oʻzbekcha', N'Oʻzbekcha', 'uz');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Venda', N'Tshivenda', N'Tshivenda', 've');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Vietnamese', N'Tiếng Việt', N'Tiếng Việt', 'vi');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Volapük', N'Volapük', N'Volapük', 'vo');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Walloon', N'Walon', N'Walon', 'wa');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Wolof', N'Wolof', N'Wolof', 'wo');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Xhosa', N'isiXhosa', N'isiXhosa', 'xh');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Yiddish', N'ייִדיש', N'Yidish', 'yi');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Yoruba', N'Yorùbá', N'Yorùbá', 'yo');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Zhuang', N'Saɯ cueŋƅ', N'Saw cuengh', 'za');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Chinese', N'中文', N'Zhōngwén', 'zh');
	INSERT INTO Language (EnglishName, OriginalName, TransliteratedName, Code) VALUES (N'Zulu', N'isiZulu', N'isiZulu', 'zu');
END